# Generated by Django 4.2.4 on 2023-08-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_news_title_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Press",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("news", models.ManyToManyField(to="news.news")),
            ],
        ),
    ]
