# Generated by Django 4.2.4 on 2023-08-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_press"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="moderated",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="moderated",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="news",
            field=models.ForeignKey(
                limit_choices_to={"moderated": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="news.news",
            ),
        ),
    ]
