# Generated by Django 4.2.4 on 2023-08-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_news_moderated_alter_comment_moderated_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["created_at"],
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
        migrations.AlterModelOptions(
            name="press",
            options={"verbose_name": "Press", "verbose_name_plural": "Press"},
        ),
        migrations.AlterField(
            model_name="comment",
            name="moderated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="news",
            field=models.ForeignKey(
                limit_choices_to={"moderated": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="news.news",
            ),
        ),
    ]
